import { StyleSheet } from "@react-pdf/renderer";
import { PDF_BRAND } from "@/lib/brand";

export const pdfStyles = StyleSheet.create({
  page: {
    fontFamily: "Roboto",
    fontSize: 10,
    paddingTop: 44,
    paddingBottom: 52,
    paddingHorizontal: 40,
    backgroundColor: "#ffffff",
    color: "#111827",
    lineHeight: 1.45,
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: PDF_BRAND.blue,
    paddingBottom: 12,
  },
  companyTitle: {
    fontSize: 20,
    fontWeight: 700,
    color: PDF_BRAND.blue,
    marginBottom: 8,
  },
  reportTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: "#111827",
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 10,
    color: "#374151",
    marginBottom: 2,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: PDF_BRAND.blue,
    marginBottom: 8,
    marginTop: 14,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  row: {
    flexDirection: "row",
    marginBottom: 6,
  },
  label: {
    width: "38%",
    fontSize: 9,
    color: "#4b5563",
    fontWeight: 700,
  },
  value: {
    width: "62%",
    fontSize: 10,
    color: "#111827",
  },
  notes: {
    fontSize: 10,
    color: "#111827",
    marginTop: 4,
    padding: 8,
    backgroundColor: "#f9fafb",
    borderRadius: 4,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#f3f4f6",
    paddingVertical: 6,
    paddingHorizontal: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#d1d5db",
    fontWeight: 700,
    fontSize: 8,
    color: "#111827",
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 5,
    paddingHorizontal: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
    fontSize: 8,
    color: "#111827",
  },
  colDate: { width: "22%", color: "#111827" },
  colUser: { width: "20%", color: "#111827" },
  colTitle: { width: "38%", color: "#111827" },
  colType: { width: "20%", color: "#111827" },
  colFile: { width: "32%", color: "#111827" },
  colCategory: { width: "18%", color: "#111827" },
  colUploader: { width: "22%", color: "#111827" },
  colDocDate: { width: "28%", color: "#111827" },
  footer: {
    position: "absolute",
    bottom: 28,
    left: 40,
    right: 40,
    fontSize: 8,
    color: "#4b5563",
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingTop: 8,
  },
  emptyText: {
    fontSize: 9,
    color: "#6b7280",
  },
});
